### PR TITLE
Copy todo list project for review

### PR DESCRIPTION
**Pull request by Muhammad0602**
### Kindly check my project. Any feedback or suggestion is appreciated.

### CODE REVIEW

**Comment by astroboyReloaded** [comment]
## Great job finding a solution for each of these functionalities, good organization overall. I tried very hard to have some suggestions for you, and here is what I could find:
- Following **HTML** best practices, it is best to avoid generic markup tags and use semantic tags whenever possible. In this case, you could replace the `<div>` with an `<article>`.
https://github.com/Muhammad0602/codeReview/blob/6be1aa35ae0ac0b03097ade814d9029af1bf7d17/src/index.html#L10
- As per the same guidelines, I suggest you use an `<h2>` here, since it is not used anywhere else:
https://github.com/Muhammad0602/codeReview/blob/6be1aa35ae0ac0b03097ade814d9029af1bf7d17/src/index.js#L16

- I can see there is nothing between these two divs:
https://github.com/Muhammad0602/codeReview/blob/6be1aa35ae0ac0b03097ade814d9029af1bf7d17/src/index.html#L10
and
https://github.com/Muhammad0602/codeReview/blob/6be1aa35ae0ac0b03097ade814d9029af1bf7d17/src/index.js#L20
**DRY **can also apply to **HTML** and in this case, I see no need for the extra div, so you could have called the first div in your **HTML** file by adding an `id` and `document.getElementById('my-list')`.
 - I noticed unused commented-out code:
 https://github.com/Muhammad0602/codeReview/blob/6be1aa35ae0ac0b03097ade814d9029af1bf7d17/src/index.js#L14
https://github.com/Muhammad0602/codeReview/blob/6be1aa35ae0ac0b03097ade814d9029af1bf7d17/src/index.js#L87
- I think with time, you'll be able to find simpler solutions and modulate them into smaller components. I can see that you already are using some ES6 syntax in your code, maybe the next step (in this project) could be to turn all of your functions into arrow functions if you are not looking into start using classes quite yet.

** Loved to see your work!**

**Comment by Muhammad0602** [comment]
### Thanks a lot for your kind suggestions @astroboyReloaded.
The div that I am using is for the whole container. Each section of that container is inside of an `article` element. I think I can use `section` or `main` for that. What do you think about it?

**Comment by Muhammad0602** [comment]
And for using `h2` I am a little confused. Is it bad to use `h3` when you don't have an `h2` element? I don't know much about it, so it would be great if you clarify it for me.

**Comment by astroboyReloaded** [comment]
- I'm sorry, I don't see any `<article>` in the code. I think that for this case it is enough to use only one `<section>` label, and the `<ul>` and `<li>`'s inside it give it a clear semantic meaning.

- Well, it is not bad per se, but it gives semantic meaning to titles, a bot can be confused about where is the second-level title, so it's best to use the hierarchy structure.

**Comment by Muhammad0602** [comment]
Hello @astroboyReloaded. I have implemented the changes; can you kindly check if I am done?

**Comment by astroboyReloaded** [comment]
## Congratulations!!! your code is approved! 👏👏👏👏👏👏👏👏
 You can merge to the main branch!

**Pull request merged**
